#!/bin/bash
# Quick Copy-Paste Commands for Health Tracker

echo "═══════════════════════════════════════════════════════════"
echo "🚀 QUICK START - Copy & Paste These Commands"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📍 You are in: /Volumes/ADATA\ SC750/Health-Tracker-App-v1.2/backend"
echo ""
echo "─────────────────────────────────────────────────────────"
echo "★ RUN THIS NOW (Development Mode):"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "  npm run dev"
echo ""
echo "─────────────────────────────────────────────────────────"
echo "Then in another terminal, test with:"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "  curl http://localhost:5001/api/health"
echo ""
echo "─────────────────────────────────────────────────────────"
echo "View Live Logs:"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "  tail -f logs/combined.log"
echo ""
echo "─────────────────────────────────────────────────────────"
echo "Alternative Commands:"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "npm start                         # Production mode"
echo "DISABLE_SCHEDULER=1 npm start     # Production (no scheduler)"
echo "npm test                          # Run tests"
echo "npm run test:coverage             # Tests with coverage"
echo "./run.sh                          # Interactive menu"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "✅ Test Results: 24 PASSED ✅"
echo "═══════════════════════════════════════════════════════════"
